#!/usr/bin/env python
"""Convert SEPs to (X)HTML - courtesy of /F

Usage: %(PROGRAM)s [options] [<seps> ...]

Options:

-u, --user
    python.org username

-b, --browse
    After generating the HTML, direct your web browser to view it
    (using the Python webbrowser module).  If both -i and -b are
    given, this will browse the on-line HTML; otherwise it will
    browse the local HTML.  If no sep arguments are given, this
    will browse SEP 0.

-i, --install
    After generating the HTML, install it and the plaintext source file
    (.txt) on python.org.  In that case the user's name is used in the scp
    and ssh commands, unless "-u username" is given (in which case, it is
    used instead).  Without -i, -u is ignored.

-l, --local
    Same as -i/--install, except install on the local machine.  Use this
    when logged in to the python.org machine (dinsdale).

-q, --quiet
    Turn off verbose messages.

-h, --help
    Print this help message and exit.

The optional arguments ``seps`` are either sep numbers or .txt files.
"""

import sys
import os
import re
import cgi
import glob
import getopt
import errno
import random
import time

REQUIRES = {'python': '2.2',
            'docutils': '0.2.7'}
PROGRAM = sys.argv[0]
RFCURL = 'http://www.faqs.org/rfcs/rfc%d.html'
SEPURL = 'sep-%04d.html'
SEPSVNURL = ('https://github.com/AuburnSPaRC/SEP/blob/gh-pages/sep-%04d.html')
SEPDIRRUL = 'http://AuburnSPaRC.github.com/SEP/'

HOST = ""                    # host for update
HDIR = "" # target host directory
LOCALVARS = "Local Variables:"

COMMENT = """<!--
This HTML is auto-generated.  DO NOT EDIT THIS FILE!  If you are writing a new
SEP, see http://ros.org/seps/sep-0001.html for instructions and links
to templates.  DO NOT USE THIS HTML FILE AS YOUR TEMPLATE!
-->"""

# The generated HTML doesn't validate -- you cannot use <hr> and <h3> inside
# <pre> tags.  But if I change that, the result doesn't look very nice...
DTD = ('<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"\n'
       '                      "http://www.w3.org/TR/REC-html40/loose.dtd">')

fixpat = re.compile("((https?|ftp):[-_a-zA-Z0-9/.+~:?#$=&,]+)|(sep-\d+(.txt)?)|"
                    "(RFC[- ]?(?P<rfcnum>\d+))|"
                    "(SEP\s+(?P<sepnum>\d+))|"
                    ".")

EMPTYSTRING = ''
SPACE = ' '
COMMASPACE = ', '

# Hotpatch docutils as PEP is actually a special module
# inside. Forgive this hack, but docutils does not appear to be
# pluggable.
import docutils.readers
import docutils.writers
import docutils_readers_sep
import docutils_writers_sep
sys.modules['docutils.readers.sep'] = docutils_readers_sep
sys.modules['docutils.writers.sep_html'] = docutils_writers_sep

def usage(code, msg=''):
    """Print usage message and exit.  Uses stderr if code != 0."""
    if code == 0:
        out = sys.stdout
    else:
        out = sys.stderr
    print >> out, __doc__ % globals()
    if msg:
        print >> out, msg
    sys.exit(code)


def fixanchor(current, match):
    text = match.group(0)
    link = None
    if (text.startswith('http:') or text.startswith('https:')
        or text.startswith('ftp:')):
        # Strip off trailing punctuation.  Pattern taken from faqwiz.
        ltext = list(text)
        while ltext:
            c = ltext.pop()
            if c not in '();:,.?\'"<>':
                ltext.append(c)
                break
        link = EMPTYSTRING.join(ltext)
    elif text.startswith('sep-') and text <> current:
        link = os.path.splitext(text)[0] + ".html"
    elif text.startswith('SEP'):
        sepnum = int(match.group('sepnum'))
        link = SEPURL % sepnum
    elif text.startswith('RFC'):
        rfcnum = int(match.group('rfcnum'))
        link = RFCURL % rfcnum
    if link:
        return '<a href="%s">%s</a>' % (cgi.escape(link), cgi.escape(text))
    return cgi.escape(match.group(0)) # really slow, but it works...


NON_MASKED_EMAILS = [
    'ausparc@googlegroups.com'
    ]

def fixemail(address, sepno):
    if address.lower() in NON_MASKED_EMAILS:
        # return hyperlinked version of email address
        return linkemail(address, sepno)
    else:
        # return masked version of email address
        parts = address.split('@', 1)
        return '%s&#32;&#97;t&#32;%s' % (parts[0], parts[1])


def linkemail(address, sepno):
    parts = address.split('@', 1)
    return ('<a href="mailto:%s&#64;%s?subject=SEP%%20%s">'
            '%s&#32;&#97;t&#32;%s</a>'
            % (parts[0], parts[1], sepno, parts[0], parts[1]))

def fixfile(inpath, input_lines, outfile):
    from email.Utils import parseaddr
    basename = os.path.basename(inpath)
    infile = iter(input_lines)
    if 0:
        # convert plaintext sep to minimal XHTML markup
        print >> outfile, DTD
        print >> outfile, '<html>'
        print >> outfile, COMMENT
        print >> outfile, '<head>'
    # head
    header = []
    sep = ""
    title = ""
    for line in infile:
        if not line.strip():
            break
        if line[0].strip():
            if ":" not in line:
                break
            key, value = line.split(":", 1)
            value = value.strip()
            header.append((key, value))
        else:
            # continuation line
            key, value = header[-1]
            value = value + line
            header[-1] = key, value
        if key.lower() == "title":
            title = value
        elif key.lower() == "sep":
            sep = value
    if sep:
        title = "SEP " + sep + " -- " + title

    # remove nav to sep index
    f = open('sep-html-template', 'r')
    tmpl = f.read()
    f.close()
    if int(sep) == 0:
        tmpl = tmpl.replace('[<b><a href="%(sepindex)s">SEP Index</a></b>]', '')
    tmpl_vars = {
        'sepindex': 'sep-0000.html',
        'sep': title,
        'sepnum': "%04d"%int(sep),
        'sephome': 'https://github.com/AuburnSPaRC/SEP/blob/gh-pages',
        'encoding': 'utf-8',
        'version': '',
        'title': 'SEP '+sep+" -- "+title,
        'stylesheet': '<link rel="stylesheet" href="sep.css" type="text/css" />',
        }

    if 0:
        if title:
            print >> outfile, '  <title>%s</title>' % cgi.escape(title)

        print >> outfile, (
            '  <link rel="STYLESHEET" href="style.css" type="text/css" />\n'
            '</head>\n'
            '<body bgcolor="white">\n'
            '<table class="navigation" cellpadding="0" cellspacing="0"\n'
            '       width="100%%" border="0">\n'
            '<tr><td class="navicon" width="150" height="35">\n'
            '<a href="../" title="ROS Home Page">ROS</a></td>\n'
            '<td class="textlinks" align="left">\n'
            '[<b><a href="../">ROS Home</a></b>]')
        if basename <> 'sep-0000.txt':
            print >> outfile, '[<b><a href=".">SEP Index</a></b>]'
        if sep:
            try:
                print >> outfile, ('[<b><a href="sep-%04d.txt">SEP Source</a>'
                                   '</b>]' % int(sep))
            except ValueError, error:
                print >> sys.stderr, ('ValueError (invalid SEP number): %s'
                                      % error)
        print >> outfile, '</td></tr></table>'

    real_outfile = outfile
    
    import cStringIO
    outfile = cStringIO.StringIO()
    print >> outfile, """<div class="header">\n<table border="0" class="rfc2822 docutils field-list" frame="void" rules="none">
<col class="field-name" /> 
<col class="field-body" /> 
<tbody valign="top">"""
    for k, v in header:
        if k.lower() in ('author', 'discussions-to'):
            mailtos = []
            for part in re.split(',\s*', v):
                if '@' in part:
                    realname, addr = parseaddr(part)
                    if k.lower() == 'discussions-to':
                        m = linkemail(addr, sep)
                    else:
                        m = fixemail(addr, sep)
                    mailtos.append('%s &lt;%s&gt;' % (realname, m))
                elif part.startswith('http:'):
                    mailtos.append(
                        '<a href="%s">%s</a>' % (part, part))
                else:
                    mailtos.append(part)
            v = COMMASPACE.join(mailtos)
        elif k.lower() in ('replaces', 'replaced-by', 'requires'):
            otherseps = ''
            for othersep in re.split(',?\s+', v):
                othersep = int(othersep)
                otherseps += '<a href="sep-%04d.html">%i</a> ' % (othersep,
                                                                  othersep)
            v = otherseps
        elif k.lower() in ('last-modified',):
            date = v or time.strftime('%d-%b-%Y',
                                      time.localtime(os.stat(inpath)[8]))
            try:
                url = SEPSVNURL % int(sep)
                v = '<a href="%s">%s</a> ' % (url, cgi.escape(date))
            except ValueError, error:
                v = date
        elif k.lower() in ('content-type',):
            url = SEPURL % 9
            sep_type = v or 'text/plain'
            v = '<a href="%s">%s</a> ' % (url, cgi.escape(sep_type))
        else:
            v = cgi.escape(v)
        print >> outfile, '  <tr class="field"><th class="field-name">%s:&nbsp;</th><td class="field-body">%s</td></tr>' \
              % (cgi.escape(k), v)
    print >> outfile, '</table>'
    print >> outfile, '</div>'
    print >> outfile, '<hr />'
    print >> outfile, '<div class="content">'
    need_pre = 1
    for line in infile:
        if line[0] == '\f':
            continue
        if line.strip() == LOCALVARS:
            break
        if line[0].strip():
            if not need_pre:
                print >> outfile, '</pre>'
            print >> outfile, '<h3>%s</h3>' % line.strip()
            need_pre = 1
        elif not line.strip() and need_pre:
            continue
        else:
            # SEP 0 has some special treatment
            if basename == 'sep-0000.txt':
                parts = line.split()
                if len(parts) > 1 and re.match(r'\s*\d{1,4}', parts[1]):
                    # This is a SEP summary line, which we need to hyperlink
                    url = SEPURL % int(parts[1])
                    if need_pre:
                        print >> outfile, '<pre>'
                        need_pre = 0
                    print >> outfile, re.sub(
                        parts[1],
                        '<a href="%s">%s</a>' % (url, parts[1]),
                        line, 1),
                    continue
                elif parts and '@' in parts[-1]:
                    # This is a sep email address line, so filter it.
                    url = fixemail(parts[-1], sep)
                    if need_pre:
                        print >> outfile, '<pre>'
                        need_pre = 0
                    print >> outfile, re.sub(
                        parts[-1], url, line, 1),
                    continue
            line = fixpat.sub(lambda x, c=inpath: fixanchor(c, x), line)
            if need_pre:
                print >> outfile, '<pre>'
                need_pre = 0
            outfile.write(line)
    if not need_pre:
        print >> outfile, '</pre>'

    print >> outfile, '</div>'

    tmpl_vars['body'] = outfile.getvalue()
    print >> real_outfile, tmpl%tmpl_vars
    if 0:
        print >> outfile, '</body>'
        print >> outfile, '</html>'

docutils_settings = None
"""Runtime settings object used by Docutils.  Can be set by the client
application when this module is imported."""

def fix_rst_sep(inpath, input_lines, outfile):
    from docutils import core
    output = core.publish_string(
        source=''.join(input_lines),
        source_path=inpath,
        destination_path=outfile.name,
        reader_name='sep',
        parser_name='restructuredtext',
        writer_name='sep_html',
        settings=docutils_settings,
        # Allow Docutils traceback if there's an exception:
        settings_overrides={'traceback': 1})
    outfile.write(output)

def get_sep_type(input_lines):
    """
    Return the Content-Type of the input.  "text/plain" is the default.
    Return ``None`` if the input is not a SEP.
    """
    sep_type = None
    for line in input_lines:
        line = line.rstrip().lower()
        if not line:
            # End of the RFC 2822 header (first blank line).
            break
        elif line.startswith('content-type: '):
            sep_type = line.split()[1] or 'text/plain'
            break
        elif line.startswith('sep: '):
            # Default SEP type, used if no explicit content-type specified:
            sep_type = 'text/plain'
    return sep_type

def get_input_lines(inpath):
    try:
        infile = open(inpath)
    except IOError, e:
        if e.errno <> errno.ENOENT: raise
        print >> sys.stderr, 'Error: Skipping missing SEP file:', e.filename
        sys.stderr.flush()
        return None
    lines = infile.read().splitlines(1) # handles x-platform line endings
    infile.close()
    return lines

def find_sep(sep_str):
    """Find the .txt file indicated by a cmd line argument"""
    if os.path.exists(sep_str):
        return sep_str
    num = int(sep_str)
    return "sep-%04d.txt" % num

def make_html(inpath, verbose=0):
    input_lines = get_input_lines(inpath)
    if input_lines is None:
        return None
    sep_type = get_sep_type(input_lines)
    if sep_type is None:
        print >> sys.stderr, 'Error: Input file %s is not a SEP.' % inpath
        sys.stdout.flush()
        return None
    elif not SEP_TYPE_DISPATCH.has_key(sep_type):
        print >> sys.stderr, ('Error: Unknown SEP type for input file %s: %s'
                              % (inpath, sep_type))
        sys.stdout.flush()
        return None
    elif SEP_TYPE_DISPATCH[sep_type] == None:
        sep_type_error(inpath, sep_type)
        return None
    outpath = os.path.splitext(inpath)[0] + ".html"
    if verbose:
        print inpath, "(%s)" % sep_type, "->", outpath
        sys.stdout.flush()
    outfile = open(outpath, "w")
    SEP_TYPE_DISPATCH[sep_type](inpath, input_lines, outfile)
    outfile.close()
    os.chmod(outfile.name, 0664)
    return outpath

def push_sep(htmlfiles, txtfiles, username, verbose, local=0):
    quiet = ""
    if local:
        if verbose:
            quiet = "-v"
        target = HDIR
        copy_cmd = "cp"
        chmod_cmd = "chmod"
    else:
        if not verbose:
            quiet = "-q"
        if username:
            username = username + "@"
        target = username + HOST + ":" + HDIR
        copy_cmd = "scp"
        chmod_cmd = "ssh %s%s chmod" % (username, HOST)
    files = htmlfiles[:]
    files.extend(txtfiles)
    files.append("style.css")
    files.append("sep.css")
    filelist = SPACE.join(files)
    rc = os.system("%s %s %s %s" % (copy_cmd, quiet, filelist, target))
    if rc:
        sys.exit(rc)
##    rc = os.system("%s 664 %s/*" % (chmod_cmd, HDIR))
##    if rc:
##        sys.exit(rc)

SEP_TYPE_DISPATCH = {'text/plain': fixfile,
                     'text/x-rst': fix_rst_sep}
SEP_TYPE_MESSAGES = {}

def check_requirements():
    # Check Python:
    try:
        from email.Utils import parseaddr
    except ImportError:
        SEP_TYPE_DISPATCH['text/plain'] = None
        SEP_TYPE_MESSAGES['text/plain'] = (
            'Python %s or better required for "%%(sep_type)s" SEP '
            'processing; %s present (%%(inpath)s).'
            % (REQUIRES['python'], sys.version.split()[0]))
    # Check Docutils:
    try:
        import docutils
    except ImportError:
        SEP_TYPE_DISPATCH['text/x-rst'] = None
        SEP_TYPE_MESSAGES['text/x-rst'] = (
            'Docutils not present for "%(sep_type)s" SEP file %(inpath)s.  '
            'See README.txt for installation.')
    else:
        installed = [int(part) for part in docutils.__version__.split('.')]
        required = [int(part) for part in REQUIRES['docutils'].split('.')]
        if installed < required:
            SEP_TYPE_DISPATCH['text/x-rst'] = None
            SEP_TYPE_MESSAGES['text/x-rst'] = (
                'Docutils must be reinstalled for "%%(sep_type)s" SEP '
                'processing (%%(inpath)s).  Version %s or better required; '
                '%s present.  See README.txt for installation.'
                % (REQUIRES['docutils'], docutils.__version__))

def sep_type_error(inpath, sep_type):
    print >> sys.stderr, 'Error: ' + SEP_TYPE_MESSAGES[sep_type] % locals()
    sys.stdout.flush()

def browse_file(sep):
    import webbrowser
    file = find_sep(sep)
    if file.endswith(".txt"):
        file = file[:-3] + "html"
    file = os.path.abspath(file)
    url = "file:" + file
    webbrowser.open(url)

def browse_remote(sep):
    import webbrowser
    file = find_sep(sep)
    if file.endswith(".txt"):
        file = file[:-3] + "html"
    url = SEPDIRRUL + file
    webbrowser.open(url)

def main(argv=None):
    # defaults
    update = 0
    local = 0
    username = ''
    verbose = 1
    browse = 0

    check_requirements()

    if argv is None:
        argv = sys.argv[1:]

    try:
        opts, args = getopt.getopt(
            argv, 'bilhqu:',
            ['browse', 'install', 'local', 'help', 'quiet', 'user='])
    except getopt.error, msg:
        usage(1, msg)

    for opt, arg in opts:
        if opt in ('-h', '--help'):
            usage(0)
        elif opt in ('-i', '--install'):
            update = 1
        elif opt in ('-l', '--local'):
            update = 1
            local = 1
        elif opt in ('-u', '--user'):
            username = arg
        elif opt in ('-q', '--quiet'):
            verbose = 0
        elif opt in ('-b', '--browse'):
            browse = 1

    if args:
        septxt = []
        html = []
        for sep in args:
            file = find_sep(sep)
            septxt.append(file)
            newfile = make_html(file, verbose=verbose)
            if newfile:
                html.append(newfile)
                if browse and not update:
                    browse_file(sep)
    else:
        # do them all
        septxt = []
        html = []
        files = glob.glob("sep-*.txt")
        files.sort()
        for file in files:
            septxt.append(file)
            newfile = make_html(file, verbose=verbose)
            if newfile:
                html.append(newfile)
        if browse and not update:
            browse_file("0")

    if update:
        push_sep(html, septxt, username, verbose, local=local)
        if browse:
            if args:
                for sep in args:
                    browse_remote(sep)
            else:
                browse_remote("0")


if __name__ == "__main__":
    main()
